apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_DATABASE: dHJ4X2JhdGNoX3Byb2Nlc3Nvcg==    # Base64 encoded 'trx_batch_processor'
  MYSQL_USER: YWRtaW4=            # Base64 encoded 'admin'
  MYSQL_PASSWORD: cGFzc3dvcmQ=    # Base64 encoded 'password'
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # Base64 encoded 'rootpassword'
